[package]
name = "simple-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substring = "1"
regex = "1"
lazy-regex = "2.3.1"
